### ISSUE TITLE
FATAL UNHANDLED EXCEPTION

### ISSUE THREAD

**Issue by wasimaftab** [blahoink/maxquant_linux_guide#1]
I tried to run the following script, but getting errors (see below)
#!/bin/sh
#SBATCH --job-name=Test_MQ
#SBATCH --output=Slurm_Scripts.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=2048
#SBATCH --time=24:0:0
#SBATCH --partition=general

source /home/waftab/.bashrc
srun mono $MQ_1_6_6_0 /work/project/becimh_005/MQ_Test/mqpar_mod.xml

######Running the above script################
(base) [waftab@master Slurm_Scripts]$ ./slurm.sh 
Configuring 

Unhandled Exception:
System.Exception: Exception during execution of external process: 25752
  at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternalProcess (System.Int32 taskIndex, System.Int32 threadIndex) [0x0019d] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.DoWork (System.Int32 taskIndex, System.Int32 threadIndex) [0x0001c] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.Work (System.Object threadIndex) [0x00054] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <f9824995c039411fb5cb6435c8065287>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Exception during execution of external process: 25752
  at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternalProcess (System.Int32 taskIndex, System.Int32 threadIndex) [0x0019d] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.DoWork (System.Int32 taskIndex, System.Int32 threadIndex) [0x0001c] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.Work (System.Object threadIndex) [0x00054] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <f9824995c039411fb5cb6435c8065287>:0 
srun: error: slim01: task 0: Exited with exit code 1
(base) [waftab@master Slurm_Scripts]$

**Comment by atc3** [comment]
Hi Wasim,

It looks like this is a problem with MaxQuant (the error message is referencing its code), and it seems that it got stuck on the Configuration step at the start. This probably means that the `mqpar.xml` file is misconfigured. You can also find more detailed error messages in the combined/proc folder. Let me know if that helps

**Comment by wasimaftab** [comment]
Hi Albert
I am getting the C++ Redistributable dependency error while running maxquant on a cluster which I do not get in my local Linux machine.

"...Microsoft Visual C++ Redistributable 2015/2017 is required to read Bruker data, but it appears not to be installed. It can be obtained here in the "redist" folder in MaxQuant installation path...." 

Because in cluster I do not have root access, I had installed mono from the source by cloning from github. On the other hand in the local machine, I installed it as follows
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
sudo apt install apt-transport-https ca-certificates
echo "deb https://download.mono-project.com/repo/ubuntu vs-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
sudo apt update

**Comment by atc3** [comment]
So this probably means that the Bruker vendor code is not compatible with the mono runtime... If you have access to a windows machine you could convert the raws to a common format like mzXML, and then feed that into MQ, but at that point you might as well process them on the same windows machine as well.

I have some Bruker data that I can try on my setup, but I'll probably run into the same error as yours -- i'll let you know

**Comment by wasimaftab** [comment]
If you do system wide installation of mono on the cluster like i did on my local machine then its unlikely you'll get that error.

**Comment by atc3** [comment]
@wasimaftab any update? I'm having trouble with reading Bruker files too, although I suspect it's a problem with the files themselves. I will try with some publicly available data instead soon

**Comment by wasimaftab** [comment]
@blahoink did not get a chance to look at this issue any further. As I said earlier, I was able to process same raw file on local machine that had issues in the cluster. Therefore, I do not feel the problem is with the files. my guess is that, on the cluster many required packages for mono to run smoothly are not installed. But I will try to debug it as soon as I am free. Meanwhile, if you get a hint then please share.

**Comment by cscaife** [comment]
@blahonik @wasimaftab 
Hi, I can run Bruker timsTOF data on my Ubuntu (16.04) machine but got the error described above when trying to process Bruker files on a server running CentOS (7.7).  The CentOS machine has no problems with Thermo files. 

We had already ruled out different Mono or MaxQuant versions, or privileges as being the issue.

After a bit of comparison between the two systems it looks like the libraries on the CentOS machine are older than those used in the compilation of MaxQuant. So we downloaded and installed gcc-8.3.0 from gnu.org.  

MQ 1.6.10.43 is now able to read the Bruker files and is currently running an analysis. There may be other issues but so far so good.

(I can't take credit for the detection I just pestered the person who figured it out :-) I also understand that you have to be careful with where you place the libraries and paths to same, and so I leave that to the true linux experts.
Hope this helps

**Comment by atc3** [comment]
@cscaife Amazing, thanks for the info! I'll add this to the blog post and readme

**Comment by wasimaftab** [comment]
@cscaife thanks for your time. after the gcc update its now able to read the files. however, it gets stuck forever at "Preparing searches" step. for more info please take a look at this link
https://maxquant.myjetbrains.com/youtrack/issue/MaxQuant-363

**Comment by atc3** [comment]
The "Preparing searches" step encompasses a lot of smaller steps (Create peptide list, create protein list, etc) - you can see exactly which ones were being run if you go to the `combined/proc` folder. Which specific step did it get stuck on?

I've also been able to get past this issue by restarting the search... I know that's not an ideal solution but thats gotten me past the preparing searches step a couple of times in the past

**Comment by wasimaftab** [comment]
@blahoink
I tried the following:
1. Installed latest mono 6.8.0.105
2. updated MQ 1.6.10.43
3. updated gcc to 9.2.0
4. started MQ search in an interactive slurm session as follows
**srun -p slim16 -I -c 64 --mem=256000 --time 100-00:00:00 --job-name=MQ_1_6_10_43 mono $MQ_1_6_10_43 mqpar_mod.xml**
and it stalled at the same point(i.e "Preparing Searches")
5. downgraded mono 6.7.0
6. downgraded MQ 1.6.6.0 
7. kept the gcc same as before and started MQ search in an interactive slurm session as follows
**srun -p slim16 -I -c 64 --mem=256000 --time 100-00:00:00 --job-name=MQ mono $MQ_1_6_6_0 mqpar_mod.xml**

AND voila!

I must say MQ's behavior is pretty unpredictable on Cent OS7 Linux at this point.
Have you/anyone seen runtime improvement by using more nodes? I mean can MQ make use of MPI calls so that allocating multiple nodes makes sense?

**Comment by cscaife** [comment]
I ran 420 Thermo files on the CentOS using 36 of its processors and making full use of the ssd on the Linux machine. Initially the run stopped at the FDR step, but I changed the vm.max_mem_count to 1000000 (found that on MaxQuant google groups) restarted using partial processing, and the analysis completed in just over 30 hours. Previously on a Windows 7 PC, with 7 processors and using an ssd for the temporary folder, it took nearly 3 weeks. Not a like for like comparison, but a huge relief.

We will probably run analyses of smaller data sets on Windows PCs and leave the larger data sets for the CentOS.

**Comment by wasimaftab** [comment]
@cscaife interesting! could you please tell the total size of 420 files approximately? because I'm processing ~872GB of timsTOF data (70 files) from Brucker machine. Also, did you test the performance before changing the vm.max_mem_count to 1000000? and all 36 processors were from a single node right?

**Comment by wasimaftab** [comment]
After having run a single raw file successfully, I went for the real job (70 files ~872GB). It caught unhandled exception at **Cluster features TIMS** step.
**(base) [waftab@master Raw2]$ srun -p slim16 -I -c 64 --mem=256000 --time 100-00:00:00 --job-name=MQ_872GB mono $MQ_1_6_6_0 mqpar_mod.xml
Configuring 
Testing fasta files 
Testing raw files 
Feature detection TIMS 
Cluster features TIMS** 

`
 Unhandled Exception:
System.Exception: Exception during execution of external process: 7576
  at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternalProcess (System.Int32 taskIndex, System.Int32 threadIndex) [0x0019d] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.DoWork (System.Int32 taskIndex, System.Int32 threadIndex) [0x0001c] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.Work (System.Object threadIndex) [0x00054] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <f9824995c039411fb5cb6435c8065287>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Exception during execution of external process: 7576
  at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternalProcess (System.Int32 taskIndex, System.Int32 threadIndex) [0x0019d] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.DoWork (System.Int32 taskIndex, System.Int32 threadIndex) [0x0001c] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at BaseLibS.Util.WorkDispatcher.Work (System.Object threadIndex) [0x00054] in <a5e2699791c9405ea93be65daa8164cf>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <f9824995c039411fb5cb6435c8065287>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <f9824995c039411fb5cb6435c8065287>:0 
`

**Comment by cscaife** [comment]
@wasimaftab The 420 files totalled approx 575 Gb. They were **_not_** Bruker  IMS files but from a QExactive.  And yes, it was run on a single node.  I couldn't do a comparison before and after changing the memory mapping as MaxQuant would just stop at the FDR step if the setting was too low. 

You may already have seen these, but here are two threads (one on Linux cluster parallelization and one on memory mapping) that may be helpful -

https://groups.google.com/d/msg/maxquant-list/7aPVF3nGeM8/pZ2ZGR3aEQAJ

https://groups.google.com/d/msg/maxquant-list/l2Ej3mdrxtU/Qy5udJ9rCAAJ

**Comment by wasimaftab** [comment]
@cscaife thanks for your time. following your suggestions, I restarted the search with increased ulimit and vm.max_map_count on a slim node with 256GB RAM and 64 cores. It complained of low memory with an _unhandled exception_. Then I restarted it on a fat node with 1.5TB RAM and 96 cores. The job was running nicely until **Preparing Searches** . At that step, it just stalled forever with no error and no output. The exact last files created are a bunch of **Creating _protein_files xxxxxx.finished.txt**, xxxxxx implies a file number. stopping and restarting seems to have no effect.

**Comment by wasimaftab** [comment]
@blahoink @cscaife 
This time I just took a single bricker file (~4.2GB) and ran mono in debug mode using MQ (1.6.11.0) on my ubuntu pc. It caught a FATAL UNHANDLED EXCEPTION at **Preparing Searches**  step. Without debug mode, it used to stall forever. Now, I need to figure out what does the `QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess ` exception mean in this context.
I will appreciate any ideas.

**`(base) wasim@DNA:~/Desktop/MQ_Command_Line/Hela$ gdb mono`**
`GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1`
`Copyright (C) 2016 Free Software Foundation, Inc.`
`License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`
`This is free software: you are free to change and redistribute it.`
`There is NO WARRANTY, to the extent permitted by law.  Type "show copying"`
`and "show warranty" for details.`
`This GDB was configured as "x86_64-linux-gnu".`
`Type "show configuration" for configuration details.`
`For bug reporting instructions, please see:`
`<http://www.gnu.org/software/gdb/bugs/>.`
`Find the GDB manual and other documentation resources online at:`
`<http://www.gnu.org/software/gdb/documentation/>.`
`For help, type "help".`
`Type "apropos word" to search for commands related to "word"...`
`Reading symbols from mono...(no debugging symbols found)...done.`
**`(gdb) run /home/wasim/Desktop/MQ_Command_Line/MaxQuant_1.6.11.0/bin/MaxQuantCmd.exe mqpar_mod_1.6.11.0.xml`**
`Starting program: /usr/bin/mono /home/wasim/Desktop/MQ_Command_Line/MaxQuant_1.6.11.0/bin/MaxQuantCmd.exe mqpar_mod_1.6.11.0.xml`
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".`
`[New Thread 0x7ffff5fff700 (LWP 20826)]`
`[New Thread 0x7ffff66e7700 (LWP 20827)]`
**`Configuring `**
`[New Thread 0x7ffff19ea700 (LWP 20828)]`
`[Thread 0x7ffff19ea700 (LWP 20828) exited]`
**`Testing fasta files `**
`[New Thread 0x7ffff19ea700 (LWP 20832)]`
`[Thread 0x7ffff19ea700 (LWP 20832) exited]`
**`Testing raw files `**
`[New Thread 0x7ffff19ea700 (LWP 20836)]`
`[Thread 0x7ffff19ea700 (LWP 20836) exited]`
**`Feature detection TIMS `**
`[New Thread 0x7ffff19ea700 (LWP 20840)]`
`[Thread 0x7ffff19ea700 (LWP 20840) exited]`
**`De-isotoping TIMS `**
`[New Thread 0x7ffff19ea700 (LWP 23564)]`
`[Thread 0x7ffff19ea700 (LWP 23564) exited]`
`MS/MS preparation TIMS first search split `
`[New Thread 0x7ffff19ea700 (LWP 23948)]`
`[New Thread 0x7ffff17e9700 (LWP 23950)]`
`[New Thread 0x7ffff15e8700 (LWP 23953)]`
`[New Thread 0x7ffff13e7700 (LWP 23958)]`
`[New Thread 0x7ffff11e6700 (LWP 23963)]`
`[New Thread 0x7ffff0fe5700 (LWP 23967)]`
`[New Thread 0x7ffff0de4700 (LWP 23970)]`
`[New Thread 0x7ffff0be3700 (LWP 23973)]`
`[New Thread 0x7ffff09e2700 (LWP 23977)]`
`[New Thread 0x7ffff07e1700 (LWP 23981)]`
`[New Thread 0x7ffff05e0700 (LWP 23986)]`
`[New Thread 0x7ffff03df700 (LWP 23989)]`
`[New Thread 0x7fffe99d5700 (LWP 23994)]`
`[New Thread 0x7fffe97d4700 (LWP 23998)]`
`[New Thread 0x7fffe95d3700 (LWP 24002)]`
`[New Thread 0x7fffe93d2700 (LWP 24006)]`
`[New Thread 0x7fffe91d1700 (LWP 24010)]`
`[New Thread 0x7fffe8fd0700 (LWP 24014)]`
`[New Thread 0x7fffe8dcf700 (LWP 24018)]`
`[New Thread 0x7fffe8bce700 (LWP 24022)]`
`[Thread 0x7ffff15e8700 (LWP 23953) exited]`
`[Thread 0x7ffff17e9700 (LWP 23950) exited]`
`[Thread 0x7ffff13e7700 (LWP 23958) exited]`
`[Thread 0x7ffff11e6700 (LWP 23963) exited]`
`[Thread 0x7ffff0fe5700 (LWP 23967) exited]`
`[Thread 0x7ffff0de4700 (LWP 23970) exited]`
`[Thread 0x7ffff0be3700 (LWP 23973) exited]`
`[Thread 0x7ffff09e2700 (LWP 23977) exited]`
`[Thread 0x7ffff07e1700 (LWP 23981) exited]`
`[Thread 0x7fffe99d5700 (LWP 23994) exited]`
`[Thread 0x7ffff05e0700 (LWP 23986) exited]`
`[Thread 0x7ffff03df700 (LWP 23989) exited]`
`[Thread 0x7fffe97d4700 (LWP 23998) exited]`
`[Thread 0x7fffe95d3700 (LWP 24002) exited]`
`[Thread 0x7fffe93d2700 (LWP 24006) exited]`
`[Thread 0x7fffe91d1700 (LWP 24010) exited]`
`[Thread 0x7fffe8fd0700 (LWP 24014) exited]`
`[Thread 0x7fffe8dcf700 (LWP 24018) exited]`
`[Thread 0x7ffff19ea700 (LWP 23948) exited]`
`[Thread 0x7fffe8bce700 (LWP 24022) exited]`
**`MS/MS preparation TIMS first search combine `**
`[New Thread 0x7fffe8bce700 (LWP 24078)]`
`[Thread 0x7fffe8bce700 (LWP 24078) exited]`
**`Calculating peak properties (TIMS) `**
`[New Thread 0x7fffe8bce700 (LWP 24084)]`
`[Thread 0x7fffe8bce700 (LWP 24084) exited]`
**`Combining tims apl files for first search `**
`[New Thread 0x7fffe8bce700 (LWP 24088)]`
`[Thread 0x7fffe8bce700 (LWP 24088) exited]`
**`Preparing searches `**
`[New Thread 0x7fffe8bce700 (LWP 24095)]`
``
`Unhandled Exception:`
`System.Exception: Exception during execution of external process: 24096`
`  at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess (System.Int32 taskIndex, System.Int32 threadIndex) [0x001a1] in <b9531545f7874c7f8c51b1af713af1b3>:0 `
`  at QueueingSystem.WorkDispatcher.DoWork (System.Int32 taskIndex, System.Int32 threadIndex) [0x0001e] in <b9531545f7874c7f8c51b1af713af1b3>:0 `
`  at QueueingSystem.WorkDispatcher.Work (System.Object threadIndex) [0x00054] in <b9531545f7874c7f8c51b1af713af1b3>:0 `
`  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x7ffff3cb0bf0 + 0x00089> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7ffff3cae620 + 0x00147> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7ffff3cae5a0 + 0x00022> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x7ffff3cae520 + 0x00034> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) <0x7ffff3cb0cd0 + 0x0004d> in <a1ae6166591d4020b810288d19af38d4>:0 `
`[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Exception during execution of external process: 24096`
`  at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess (System.Int32 taskIndex, System.Int32 threadIndex) [0x001a1] in <b9531545f7874c7f8c51b1af713af1b3>:0 `
`  at QueueingSystem.WorkDispatcher.DoWork (System.Int32 taskIndex, System.Int32 threadIndex) [0x0001e] in <b9531545f7874c7f8c51b1af713af1b3>:0 `
`  at QueueingSystem.WorkDispatcher.Work (System.Object threadIndex) [0x00054] in <b9531545f7874c7f8c51b1af713af1b3>:0 `
`  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x7ffff3cb0bf0 + 0x00089> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7ffff3cae620 + 0x00147> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x7ffff3cae5a0 + 0x00022> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x7ffff3cae520 + 0x00034> in <a1ae6166591d4020b810288d19af38d4>:0 `
`  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) <0x7ffff3cb0cd0 + 0x0004d> in <a1ae6166591d4020b810288d19af38d4>:0 `
`[Thread 0x7fffe8bce700 (LWP 24095) exited]`
`[Thread 0x7ffff5fff700 (LWP 20826) exited]`
`[Thread 0x7ffff7fc7780 (LWP 20822) exited]`
`[Inferior 1 (process 20822) exited with code 01]`
``

**Comment by cscaife** [comment]
@wasimaftab
It may be an issue with MQ 1.6.11.0
I ran 6 timsTOF files on the CentOS using MQ 1.6.10.43 and everything ran fine.
I repeated the run using MQ 1.6.11.0 and it stopped at the same point as yours. I am getting the following error messages in the combined->proc folder 
An issue with TensorFlowSharp or one of its dependencies being missing

[MSMS_first_search 0620.error.txt](https://github.com/blahoink/maxquant_linux_guide/files/4312524/MSMS_first_search.0620.error.txt)

This has also been reported on the MaxQuant group and the response seems to be from a person in the MaxQuant group so hopefully they will fix the problem.
https://groups.google.com/d/msg/maxquant-list/pNGlhXRYgjU/Ekwd7W6BAAAJ

**Comment by wasimaftab** [comment]
@cscaife I tried running today on ubuntu 18.04 and I got TensorFlowSharp missing error. This thefirst time I got any error message in the proc folder. But earlier when I tried on cluster I did not get any error messages. It just stalled. Also, on my other ubuntu 16.04 pc it stalls without any error messages. I mean in the proc folder there is no text file with error message. All I saw there a bunch of started and finished text files. Thanks a lot for the error message :), without that I could have never got to know what exactly in going behind the scene.
Then, I just copied the following two files from bin folder of last release (1.6.10.43) into the latest one
 1. libtensorflow.dll
 2. TensorFlowSharp.dll
and the problem was solved.
Don't know whether the same hack will be effective in cent OS

**Comment by wasimaftab** [comment]
Update: this error is not appearing anymore on mq 1.6.15.0 version which uses dot net core. I guess dot net core makes it run smoothly on cross platforms. Therefore, anyone if getting this error in future, check your gcc version and upgrade it as suggested in this thread and use proper dot net core version.
